"use client";

import React, { useState, useRef } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ShieldCheck, ArrowRight, Lock, KeyRound, Loader2, RotateCcw, ArrowUpRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Logo } from "@/components/ui/logo";

export default function MFAVerifyPage() {
  const router = useRouter();
  const [code, setCode] = useState<string[]>(["", "", "", "", "", ""]);
  const [loading, setLoading] = useState(false);
  const inputsRef = useRef<(HTMLInputElement | null)[]>([]);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>, index: number) => {
    const val = e.target.value;
    if (val.length <= 1) {
      const newCode = [...code];
      newCode[index] = val;
      setCode(newCode);

      if (val && index < 5) {
        inputsRef.current[index + 1]?.focus();
      }
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>, index: number) => {
    if (e.key === "Backspace" && !code[index] && index > 0) {
      inputsRef.current[index - 1]?.focus();
    }
  };

  const handleVerify = (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setTimeout(() => {
      setLoading(false);
      router.push("/overview");
    }, 600);
  };

  return (
    <div className="min-h-screen w-full flex flex-col lg:grid lg:grid-cols-12 bg-slate-50/50 text-slate-900 font-sans selection:bg-emerald-600 selection:text-white antialiased">
      {/* ── Left Side: Clean Architectural Context (7 Cols) ──────────────── */}
      <div className="hidden lg:flex lg:col-span-7 relative flex-col justify-between p-8 xl:p-12 bg-white border-r border-slate-200/80 shadow-[inset_-1px_0_0_rgba(0,0,0,0.02)] overflow-hidden">
        <div
          className="absolute inset-0 opacity-[0.4]"
          style={{
            backgroundImage: "radial-gradient(circle at 1px 1px, #e2e8f0 1px, transparent 0)",
            backgroundSize: "20px 20px",
          }}
        />

        <div className="relative z-10">
          <Logo href="/" iconSize="sm" subtitle="Security Protocol" />
        </div>

        <div className="relative z-10 my-auto max-w-lg space-y-5 py-4">
          <div className="space-y-2">
            <div className="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full bg-emerald-50 border border-emerald-200 text-emerald-700 text-[11px] font-bold">
              <KeyRound className="size-3.5" />
              <span>Two-Factor Checkpoint</span>
            </div>

            <h1 className="text-2xl xl:text-3xl font-black tracking-tight text-slate-900 leading-snug">
              Confirm Authorized <br />
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-emerald-600 to-teal-600">
                Staff Identity.
              </span>
            </h1>

            <p className="text-xs sm:text-[13px] text-slate-600 font-medium leading-relaxed">
              Enter the 6-digit authentication token generated by your mobile authenticator to verify your administrative session.
            </p>
          </div>

          <div className="p-3.5 rounded-xl bg-slate-50 border border-slate-200/80 flex items-center gap-3">
            <div className="size-8 rounded-lg bg-emerald-100 text-emerald-700 flex items-center justify-center font-bold">
              <ShieldCheck className="size-4" />
            </div>
            <div>
              <p className="text-xs font-bold text-slate-900">Cryptographic Session Key</p>
              <p className="text-[11px] text-slate-500 font-medium">Auto-refreshes every 30 seconds.</p>
            </div>
          </div>
        </div>

        <div className="relative z-10 pt-3 border-t border-slate-200/60 flex items-center justify-between text-[11px] text-slate-500 font-medium">
          <p>© {new Date().getFullYear()} Crown Paints Kenya PLC</p>
          <Link href="/auth/login" className="hover:text-emerald-700 transition-colors flex items-center gap-0.5">
            <span>Back to Login</span>
            <ArrowUpRight className="size-3" />
          </Link>
        </div>
      </div>

      {/* ── Right Side: 6-Digit PIN Form (5 Cols) ─────────────────────────── */}
      <div className="lg:col-span-5 flex flex-col justify-between p-6 sm:p-8 xl:p-10 bg-slate-50/40 relative overflow-y-auto">
        <div className="lg:hidden flex items-center justify-between mb-6 pb-3 border-b border-slate-200">
          <Logo href="/" iconSize="sm" />
          <Link href="/auth/login">
            <Button size="sm" variant="ghost" className="text-xs font-bold h-7">
              Sign In
            </Button>
          </Link>
        </div>

        <div className="my-auto max-w-sm w-full mx-auto space-y-4 text-center">
          <div className="space-y-1">
            <div className="inline-flex items-center gap-1 px-2 py-0.5 rounded bg-emerald-100/70 text-emerald-800 text-[10px] font-black uppercase tracking-wider">
              <Lock className="size-2.5" /> Step 2 of 2
            </div>
            <h2 className="text-xl sm:text-2xl font-black text-slate-900 tracking-tight">
              Enter Verification Code
            </h2>
            <p className="text-xs text-slate-500 font-medium">
              Enter the 6-digit code shown in your authenticator app.
            </p>
          </div>

          <form onSubmit={handleVerify} className="space-y-4">
            <div className="grid grid-cols-6 gap-1.5 sm:gap-2">
              {[0, 1, 2, 3, 4, 5].map((idx) => (
                <input
                  key={idx}
                  ref={(el) => { inputsRef.current[idx] = el; }}
                  type="text"
                  inputMode="numeric"
                  pattern="[0-9]*"
                  maxLength={1}
                  value={code[idx]}
                  onChange={(e) => handleChange(e, idx)}
                  onKeyDown={(e) => handleKeyDown(e, idx)}
                  autoFocus={idx === 0}
                  className="size-11 sm:size-12 text-center text-lg font-black rounded-lg border border-slate-300 bg-white focus:border-emerald-600 focus:ring-2 focus:ring-emerald-600/15 text-slate-900 transition-all shadow-sm"
                />
              ))}
            </div>

            <Button
              type="submit"
              disabled={loading || code.some((c) => !c)}
              className="w-full h-9 bg-emerald-600 hover:bg-emerald-700 text-white rounded-lg font-black text-xs shadow-sm transition-all flex items-center justify-center gap-1.5 disabled:opacity-50 cursor-pointer"
            >
              {loading ? (
                <>
                  <Loader2 className="size-3.5 animate-spin" />
                  <span>VERIFYING CODE…</span>
                </>
              ) : (
                <>
                  <span>AUTHENTICATE SESSION</span>
                  <ArrowRight className="size-3.5" />
                </>
              )}
            </Button>
          </form>

          <div className="flex items-center justify-between text-xs font-semibold text-slate-500 pt-1">
            <Link href="/auth/mfa/setup" className="hover:text-emerald-700 transition-colors flex items-center gap-1">
              <RotateCcw className="size-3" /> Re-scan QR
            </Link>
            <Link href="/auth/login" className="hover:text-emerald-700 transition-colors">
              Cancel & Sign In
            </Link>
          </div>
        </div>

        <div className="pt-4 border-t border-slate-200 text-center text-[11px] text-slate-500 font-medium">
          Protected by Enterprise Session Encryption.
        </div>
      </div>
    </div>
  );
}
